
redisAddress: redis://myproject-redis-redis-cluster:6379

serviceMonitor:
  enabled: true
  # Set the namespace the ServiceMonitor should be deployed
  # namespace: monitoring
  # Set how frequently Prometheus should scrape
  interval: 5s
  # Set path to redis-exporter telemtery-path
  telemetryPath: /metrics
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  labels:
    release: base-prometheus-stack
  # labels:
  # Set timeout for scrape
  # timeout: 10s
  # Set of labels to transfer on the Kubernetes Service onto the target.
  # targetLabels: []
  # metricRelabelings: []

auth:
  # Use password authentication
  enabled: false
  # Use existing secret (ignores redisPassword)
  # secret:
  #   name: "redis-db-secret"
  #   key: "password"
  # Redis password (when not stored in a secret)
  # redisPassword: ""

